name: Deploy
on:
   push:
      branches:
         - master

jobs:
   prettier:
      name: Check prettier
      runs-on: ubuntu-latest
      steps:
         - name: Checkout source code
           uses: actions/checkout@v2
         - name: Load cache
           uses: actions/cache@v2
           with:
              path: '**/node_modules'
              key: ${{ runner.os }}-modules
         - name: Install dependencies
           run: npm install
         - name: Checking files formatting
           run: npm run check:prettier

   typescript:
      name: Check typescript
      runs-on: ubuntu-latest
      steps:
         - name: Checkout source code
           uses: actions/checkout@v2
         - name: Load cache
           uses: actions/cache@v2
           with:
              path: '**/node_modules'
              key: ${{ runner.os }}-modules
         - name: Install dependencies
           run: npm install
         - name: Generate prisma schema
           run: npx prisma generate
         - name: Running typescript validation
           run: npm run check:typescript

   eslint:
      name: Check eslint
      runs-on: ubuntu-latest
      steps:
         - name: Checkout source code
           uses: actions/checkout@v2
         - name: Load cache
           uses: actions/cache@v2
           with:
              path: '**/node_modules'
              key: ${{ runner.os }}-modules
         - name: Install dependencies
           run: npm install
         - name: Running linter
           run: npm run check:eslint

   unit_tests:
      name: Unit tests
      runs-on: ubuntu-latest
      needs: [prettier, typescript, eslint]
      steps:
         - name: Checkout source code
           uses: actions/checkout@v2
         - name: Install dependencies
           run: npm install
         - name: Running unit tests
           run: npm run tests --ci

   integration_tests:
      name: Integration tests
      runs-on: ubuntu-latest
      needs: [prettier, typescript, eslint]
      steps:
         - name: Checkout source code
           uses: actions/checkout@v2
         - name: Running integration tests
           uses: cypress-io/github-action@v2
           with:
              command: npm run tests:e2e:ci

   production:
      name: Production
      runs-on: ubuntu-latest
      needs: [unit_tests, integration_tests]
      steps:
         - name: Checkout source code
           uses: actions/checkout@v2
         - name: Load cache
           uses: actions/cache@v2
           with:
              path: '**/node_modules'
              key: ${{ runner.os }}-modules
         - name: Install dependencies
           run: npm install
         - name: Generate prisma schema
           run: npx prisma generate
         - name: Build
           run: npm run build
         - name: Pulling changes & migrating database
           uses: appleboy/ssh-action@master
           with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              key: ${{ secrets.SSHKEY }}
              port: ${{ secrets.PORT }}
              script: |
                 /usr/bin/git -C ~/taktix pull
                 cd ~/taktix && /root/.nvm/versions/node/v15.12.0/bin/npx prisma migrate deploy
         - name: Copy build using SCP
           uses: appleboy/scp-action@master
           env:
              HOST: ${{ secrets.HOST }}
              USERNAME: ${{ secrets.USERNAME }}
              PORT: ${{ secrets.PORT }}
              KEY: ${{ secrets.SSHKEY }}
           with:
              source: '.next/.'
              target: '~/taktix/'
              overwrite: true
         - name: Reloading PM2 process
           uses: appleboy/ssh-action@master
           with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              key: ${{ secrets.SSHKEY }}
              port: ${{ secrets.PORT }}
              script: /usr/local/bin/pm2 reload "Taktix"
